// Create data type for FridgeItems matching data
export type FridgeItem = {
    id: number,
    name: string,
    category: string,
    price: string,
    quantity: string,
    expiry: string,
    image: any,
};

export const FridgeItems: FridgeItem[] = [
    {
        id: 1,
        name: "Apple",
        category: "Fruit",
        price: "$2.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/apple-01.jpg"),
    },
    {
        id: 2,
        name: "Banana",
        category: "Fruit",
        price: "$3.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/bananas-01.jpg"),
    },
    {
        id: 3,
        name: "Spinach",
        category: "Vegetable",
        price: "$1.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/spinach.png"),
    },

    {
        id: 4,  
        name: "Tomato",
        category: "Vegetable",
        price: "$2.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/tomato.jpg"),
    },
    {
        id: 5,
        name: "Apple",
        category: "Fruit",
        price: "$2.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/apple-01.jpg"),
    },
    {
        id: 6,
        name: "Banana",
        category: "Fruit",
        price: "$3.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/bananas-01.jpg"),
    },
    {
        id: 7,
        name: "Spinach",
        category: "Vegetable",
        price: "$1.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/spinach.png"),
    },

    {
        id: 8,
        name: "Tomato",
        category: "Vegetable",
        price: "$2.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/tomato.jpg"),
    },
    {
        id: 9,
        name: "Apple",
        category: "Fruit",
        price: "$2.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/apple-01.jpg"),
    },
    {
        id: 10,
        name: "Banana",
        category: "Fruit",
        price: "$3.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/bananas-01.jpg"),
    },
    {
        id: 11,
        name: "Spinach",
        category: "Vegetable",
        price: "$1.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/spinach.png"),
    },
    {
        id: 12,
        name: "Tomato",
        category: "Vegetable",
        price: "$2.00",
        quantity: "100gr",
        expiry: "1/1/2021",
        image: require("./assets/images/tomato.jpg"),
    },
];
